"""Generates tools/*.py from spec/kbsec_api_spec.json + spec/tool_metadata.yaml.

Run manually after updating either input file:
    python scripts/generate_tools.py
"""
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "spec" / "kbsec_api_spec.json"
METADATA_PATH = ROOT / "spec" / "tool_metadata.yaml"
TOOLS_DIR = ROOT / "tools"

HEADER = '''"""Generated by scripts/generate_tools.py — do not edit by hand.

Regenerate with: python scripts/generate_tools.py
Source: spec/kbsec_api_spec.json + spec/tool_metadata.yaml
"""
from app import mcp
from client import call


'''


def load_spec_by_code() -> dict:
    apis = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    return {api["code"]: api for api in apis}


def load_metadata() -> dict:
    return yaml.safe_load(METADATA_PATH.read_text(encoding="utf-8"))


def _collapse_whitespace(text: str) -> str:
    return " ".join(text.split())


def _param_decl(inp: dict) -> str:
    is_array = str(inp["length"]).startswith("Object")
    py_type = "list[dict]" if is_array else "str"
    if inp["required"] == "Y" and not is_array:
        return f"{inp['field']}: {py_type}"
    return f"{inp['field']}: {py_type} | None = None"


def _build_signature(inputs: list) -> str:
    decls = [_param_decl(inp) for inp in inputs]
    required = [d for d in decls if "=" not in d]
    optional = [d for d in decls if "=" in d]
    return ", ".join(required + optional)


def _describe_param(inp: dict) -> str:
    required = "필수" if inp["required"] == "Y" else "선택"
    note = _collapse_whitespace(str(inp.get("note") or ""))
    suffix = f" {note}" if note else ""
    return f"{inp['field']}: {inp['kor']} ({required}).{suffix}"


def _name_based_description(api: dict) -> str:
    """Derive a fallback description from the excel 요약 sheet's API명 column.

    e.g. name="SSAM1806_취소주문", code="SSAM1806" -> "취소주문"
    """
    name = _collapse_whitespace(str(api.get("name") or ""))
    code = api.get("code") or ""
    prefix = f"{code}_"
    if name.startswith(prefix):
        return name[len(prefix):]
    return name


def _build_docstring(api: dict) -> str:
    desc = (
        _collapse_whitespace(api["desc"])
        or _name_based_description(api)
        or f"{api['code']} API 호출"
    )
    lines = [desc, "", f"KB증권 API: {api['code']} (POST {api['path']})"]
    if api["inputs"]:
        lines += ["", "Args:"]
        for inp in api["inputs"]:
            lines.append(f"    {_describe_param(inp)}")
    return "\n    ".join(lines)


def _build_body(inputs: list) -> str:
    if not inputs:
        return "    body: dict = {}\n"
    lines = ["    body = {"]
    for inp in inputs:
        lines.append(f'        "{inp["field"]}": {inp["field"]},')
    lines.append("    }")
    lines.append("    body = {k: v for k, v in body.items() if v is not None}\n")
    return "\n".join(lines) + "\n"


def render_function(tool_name: str, api: dict) -> str:
    signature = _build_signature(api["inputs"])
    docstring = _build_docstring(api)
    body = _build_body(api["inputs"])
    return (
        f"@mcp.tool()\n"
        f"async def {tool_name}({signature}) -> dict:\n"
        f'    """{docstring}\n    """\n'
        f"{body}"
        f'    return await call("{api["path"]}", body)\n'
    )


def generate() -> None:
    spec_by_code = load_spec_by_code()
    metadata = load_metadata()

    for file_stem, entries in metadata.items():
        functions = [render_function(entry["tool_name"], spec_by_code[entry["code"]]) for entry in entries]
        content = HEADER + "\n\n".join(functions) + "\n"
        (TOOLS_DIR / f"{file_stem}.py").write_text(content, encoding="utf-8")
        print(f"Wrote {len(entries)} tools to tools/{file_stem}.py")


if __name__ == "__main__":
    generate()
