"""Generated by scripts/generate_tools.py — do not edit by hand.

Regenerate with: python scripts/generate_tools.py
Source: spec/kbsec_api_spec.json + spec/tool_metadata.yaml
"""
from app import mcp
from client import call


@mcp.tool()
async def orderhist_kr_get_reserve_order_result(ordr_dt: str, trd_clsf: str, hndl_clsf: str, tv_rv_ccd: str, nxt_key: str | None = None, end_dt: str | None = None, is_cd: str | None = None) -> dict:
    """사전에 접수된 예약 주문의 처리 결과를 조회합니다.예약 주문 접수 후 실제 시장 개장 시 처리된 체결 여부와 결과를 확인할 수 있습니다.
    
    KB증권 API: SSQM0831 (POST /api/v1/ssqm0831)
    
    Args:
        ordr_dt: 주문일자 (필수).
        nxt_key: 다음키 (선택).
        trd_clsf: 매매구분 (필수). 0:전체,1:매도,2:매수
        hndl_clsf: 처리구분 (필수). 0:전체,S:완료,R:접수,E:거부
        tv_rv_ccd: 전량잔량구분코드 (필수). 0:전체,N:일반,T:기간
        end_dt: 종료일자 (선택).
        is_cd: 종목코드 (선택).
    """
    body = {
        "ordr_dt": ordr_dt,
        "nxt_key": nxt_key,
        "trd_clsf": trd_clsf,
        "hndl_clsf": hndl_clsf,
        "tv_rv_ccd": tv_rv_ccd,
        "end_dt": end_dt,
        "is_cd": is_cd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssqm0831", body)


@mcp.tool()
async def orderhist_kr_get_reserve_order_list(nxt_key: str | None = None, strt_dt: str | None = None, end_dt: str | None = None, is_cd: str | None = None) -> dict:
    """접수된 예약 주문 내역을 조회합니다.정규 시장 시간 외에 접수한 예약 주문의 종목, 수량, 단가 등 상세 내역을 확인할 수 있습니다.
    
    KB증권 API: SSQM0834 (POST /api/v1/ssqm0834)
    
    Args:
        nxt_key: 다음키 (선택).
        strt_dt: 시작일자 (선택).
        end_dt: 종료일자 (선택).
        is_cd: 종목코드 (선택).
    """
    body = {
        "nxt_key": nxt_key,
        "strt_dt": strt_dt,
        "end_dt": end_dt,
        "is_cd": is_cd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssqm0834", body)


@mcp.tool()
async def orderhist_kr_get_order_execution_status(ccls_clsf: str, ordr_dt: str, nxt_key: str | None = None) -> dict:
    """계좌별 주문 체결 내역을 조회합니다.지정된 기간 내 체결된 주문의 종목, 매매 구분, 체결 수량, 단가, 수수료 등을 확인할 수 있습니다.
    
    KB증권 API: SSQM2341 (POST /api/v1/ssqm2341)
    
    Args:
        ccls_clsf: 체결구분 (필수). 0:전체, 1:체결, 2:미체결
        ordr_dt: 주문일자 (필수).
        nxt_key: 다음키 (선택).
    """
    body = {
        "ccls_clsf": ccls_clsf,
        "ordr_dt": ordr_dt,
        "nxt_key": nxt_key,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssqm2341", body)


@mcp.tool()
async def orderhist_kr_get_fractional_trade_history(trd_clsf: str, trd_strt_dt: str, trd_end_dt: str | None = None, is_cd: str | None = None, nxt_key: str | None = None) -> dict:
    """국내주식 소수점 매매 전체 내역을 조회합니다.소수점 단위로 매수·매도한 거래 내역, 수량, 금액, 손익을 기간별로 확인할 수 있습니다.
    
    KB증권 API: SSQM5765 (POST /api/v1/ssqm5765)
    
    Args:
        trd_clsf: 매매구분 (필수). 0: 전체, 1:매도, 2:매수
        trd_strt_dt: 매매시작일자 (필수).
        trd_end_dt: 매매종료일자 (선택). * 당일자 조회시에는 빈값
        is_cd: 종목코드 (선택).
        nxt_key: 다음키 (선택).
    """
    body = {
        "trd_clsf": trd_clsf,
        "trd_strt_dt": trd_strt_dt,
        "trd_end_dt": trd_end_dt,
        "is_cd": is_cd,
        "nxt_key": nxt_key,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssqm5765", body)

