"""Generated by scripts/generate_tools.py — do not edit by hand.

Regenerate with: python scripts/generate_tools.py
Source: spec/kbsec_api_spec.json + spec/tool_metadata.yaml
"""
from app import mcp
from client import call


@mcp.tool()
async def account_kr_get_deposit_details(is_no: str | None = None) -> dict:
    """SSQM0004 API 호출
    
    KB증권 API: SSQM0004 (POST /api/v1/ssqm0004)
    
    Args:
        is_no: 종목번호 (선택).
    """
    body = {
        "is_no": is_no,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssqm0004", body)


@mcp.tool()
async def account_kr_get_holdings(inq_clsf: str, mkt_tm_ccd: str, is_no: str | None = None, nxt_key: str | None = None) -> dict:
    """계좌에서 보유 중인 주식 목록과 상세 정보를 조회합니다.종목별 보유 수량, 평균 매입 단가, 현재 평가금액, 손익 등을 확인할 수 있습니다.
    
    KB증권 API: SSQM1801 (POST /api/v1/ssqm1801)
    
    Args:
        inq_clsf: 조회구분 (필수). 0:현금주식매도,1:현금주식예약,2:현금주식일괄매도,3:ELW+현금,4:장외단주매도,5:ELW 전용,6:현금주식매도+코넥스+ETN,7:코넥스전용,8:ETN 전용,9:ELW+현금+ETN
        is_no: 종목번호 (선택).
        mkt_tm_ccd: 시장시간구분코드 (필수). 1:정규시장,2:장개시전시간외,3:장종료후시간외,4:시간외단일가
        nxt_key: 다음키 (선택).
    """
    body = {
        "inq_clsf": inq_clsf,
        "is_no": is_no,
        "mkt_tm_ccd": mkt_tm_ccd,
        "nxt_key": nxt_key,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssqm1801", body)


@mcp.tool()
async def account_kr_get_settlement_status(trd_dt: str, clsf: str, stmt_dt: str | None = None, nxt_key: str | None = None) -> dict:
    """SSQM2121 API 호출
    
    KB증권 API: SSQM2121 (POST /api/v1/ssqm2121)
    
    Args:
        trd_dt: 매매일자 (필수).
        clsf: 구분 (필수). 1: 단가별, 2: 종목별
        stmt_dt: 결제일자 (선택).
        nxt_key: 다음키 (선택).
    """
    body = {
        "trd_dt": trd_dt,
        "clsf": clsf,
        "stmt_dt": stmt_dt,
        "nxt_key": nxt_key,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssqm2121", body)


@mcp.tool()
async def account_kr_get_trading_profit_loss(ordr_dt_from: str, ordr_dt_to: str, is_no: str | None = None, nxt_key: str | None = None) -> dict:
    """지정된 기간 동안 계좌의 매매 손익 현황을 조회합니다.종목코드를 지정하면 특정 종목의 손익을, 미입력 시 전체 종목의 손익 합계를 조회합니다.
    
    KB증권 API: SSQM2392 (POST /api/v1/ssqm2392)
    
    Args:
        is_no: 종목번호 (선택).
        ordr_dt_from: 주문일자FROM (필수).
        ordr_dt_to: 주문일자TO (필수).
        nxt_key: 다음키 (선택).
    """
    body = {
        "is_no": is_no,
        "ordr_dt_from": ordr_dt_from,
        "ordr_dt_to": ordr_dt_to,
        "nxt_key": nxt_key,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssqm2392", body)


@mcp.tool()
async def account_kr_get_realized_profit_loss(inq_strt_dt: str, inq_end_dt: str, is_cd: str | None = None, nxt_key: str | None = None) -> dict:
    """일자별 실현 손익 내역을 상세하게 조회합니다.매매일, 종목명, 체결 수량·단가, 수수료, 제세금, 실현 손익 및 수익률을 날짜 범위별로 확인할 수 있습니다.
    
    KB증권 API: SSQM2442 (POST /api/v1/ssqm2442)
    
    Args:
        is_cd: 종목코드 (선택).
        inq_strt_dt: 조회시작일자 (필수).
        inq_end_dt: 조회종료일자 (필수).
        nxt_key: 다음키 (선택).
    """
    body = {
        "is_cd": is_cd,
        "inq_strt_dt": inq_strt_dt,
        "inq_end_dt": inq_end_dt,
        "nxt_key": nxt_key,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssqm2442", body)


@mcp.tool()
async def account_kr_get_balance_settlement_basis(inq_clsf: str | None = None, excg_mktpr_ccd: str | None = None) -> dict:
    """종합위탁계좌 및 신연금저축계좌의 잔고 현황을 조회합니다.계좌 유형별 보유 자산 및 평가 금액을 한눈에 확인할 수 있습니다.
    
    KB증권 API: SSQM2932 (POST /api/v1/ssqm2932)
    
    Args:
        inq_clsf: 조회구분 (선택). 1:계좌별, 2:상품유형별 (자문/일임)
        excg_mktpr_ccd: 거래소시세구분코드 (선택). A:통합시세,K:KRX시세,N:NXT시세
    """
    body = {
        "inq_clsf": inq_clsf,
        "excg_mktpr_ccd": excg_mktpr_ccd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssqm2932", body)


@mcp.tool()
async def account_kr_get_balance_trade_basis(excg_mktpr_ccd: str | None = None) -> dict:
    """계좌에 연결된 전체 자산의 현재 평가 금액을 조회합니다.주식, 금융상품, 예수금을 포함한 총 자산 평가를 제공하며, 전일 대비 손익도 함께 확인할 수 있습니다.
    
    KB증권 API: SSQM2952 (POST /api/v1/ssqm2952)
    
    Args:
        excg_mktpr_ccd: 거래소시세구분코드 (선택). A:통합시세, K:KRX시세, N:NXT시세
    """
    body = {
        "excg_mktpr_ccd": excg_mktpr_ccd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssqm2952", body)


@mcp.tool()
async def account_kr_get_transaction_history(strt_dt: str, end_dt: str, is_no: str | None = None, nxt_key: str | None = None, srt_clsf: str | None = None) -> dict:
    """위탁, 금융상품, 저축 계좌의 거래 내역을 기간별로 조회합니다.입출금, 매매, 배당 등 계좌 원장 상의 모든 거래 기록을 확인할 수 있습니다.
    
    KB증권 API: SWQA2301 (POST /api/v1/swqa2301)
    
    Args:
        strt_dt: 시작일자 (필수).
        end_dt: 종료일자 (필수).
        is_no: 종목번호 (선택).
        nxt_key: 다음키 (선택).
        srt_clsf: 정렬구분 (선택). 1: 과거거래내역순, 2: 최근거래내역순
    """
    body = {
        "strt_dt": strt_dt,
        "end_dt": end_dt,
        "is_no": is_no,
        "nxt_key": nxt_key,
        "srt_clsf": srt_clsf,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/swqa2301", body)


@mcp.tool()
async def account_kr_get_transaction_history_detail(inq_dt: str, dl_sq: str | None = None, nxt_key: str | None = None) -> dict:
    """SWQM2412 API 호출
    
    KB증권 API: SWQM2412 (POST /api/v1/swqm2412)
    
    Args:
        inq_dt: 조회일자 (필수).
        dl_sq: 거래일련번호 (선택).
        nxt_key: 다음키 (선택).
    """
    body = {
        "inq_dt": inq_dt,
        "dl_sq": dl_sq,
        "nxt_key": nxt_key,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/swqm2412", body)


@mcp.tool()
async def account_kr_get_withdrawable_amount(ccd: str | None = None) -> dict:
    """D+1(익일), D+2(익익일) 출금 가능 금액을 조회합니다. 주식 매도 후 결제 일정에 따른 향후 출금 가능 금액을 미리 확인할 수 있습니다.
    
    KB증권 API: SWQN2302 (POST /api/v1/swqn2302)
    
    Args:
        ccd: 구분코드 (선택). 1:익일예수금/익익일예수금 포함
    """
    body = {
        "ccd": ccd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/swqn2302", body)

