"""Generated by scripts/generate_tools.py — do not edit by hand.

Regenerate with: python scripts/generate_tools.py
Source: spec/kbsec_api_spec.json + spec/tool_metadata.yaml
"""
from app import mcp
from client import call


@mcp.tool()
async def market_kr_get_market_liquidity_trend() -> dict:
    """증시주변자금동향
    
    KB증권 API: IVA10370 (POST /api/v1/iva10370)
    """
    body: dict = {}
    return await call("/api/v1/iva10370", body)


@mcp.tool()
async def market_kr_get_world_indices(lnd_clsf: str) -> dict:
    """세계지수
    
    KB증권 API: IVA60140 (POST /api/v1/iva60140)
    
    Args:
        lnd_clsf: 대륙구분 (필수). S: 아시아, C: 아메라키, E: 유럽
    """
    body = {
        "lnd_clsf": lnd_clsf,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/iva60140", body)


@mcp.tool()
async def market_kr_get_exchange_rates() -> dict:
    """환율종합
    
    KB증권 API: IVA60190 (POST /api/v1/iva60190)
    """
    body: dict = {}
    return await call("/api/v1/iva60190", body)


@mcp.tool()
async def market_kr_get_sector_ranking(mkt_clsf: str | None = None) -> dict:
    """업종랭킹(MTS)(IVM30010)
    
    KB증권 API: IVM30010 (POST /api/v1/ivm30010)
    
    Args:
        mkt_clsf: 시장구분 (선택). 1:코스피 2:코스닥
    """
    body = {
        "mkt_clsf": mkt_clsf,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivm30010", body)


@mcp.tool()
async def market_kr_get_market_summary() -> dict:
    """시장종합(IVSA0070)
    
    KB증권 API: IVSA0070 (POST /api/v1/ivsa0070)
    """
    body: dict = {}
    return await call("/api/v1/ivsa0070", body)

