"""Generated by scripts/generate_tools.py — do not edit by hand.

Regenerate with: python scripts/generate_tools.py
Source: spec/kbsec_api_spec.json + spec/tool_metadata.yaml
"""
from app import mcp
from client import call


@mcp.tool()
async def quote_kr_get_orderbook(is_cd: str, ovtm_mkt_clsf: str | None = None) -> dict:
    """특정 종목의 조회 시점 호가 정보 조회 하는 API
    
    KB증권 API: IVU10070 (POST /api/v1/ivu10070)
    
    Args:
        is_cd: 종목코드 (필수).
        ovtm_mkt_clsf: 시간외장구분 (선택). 0:정규장, 1:시간외
    """
    body = {
        "is_cd": is_cd,
        "ovtm_mkt_clsf": ovtm_mkt_clsf,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivu10070", body)


@mcp.tool()
async def quote_kr_get_time_trades(is_cd: str, excg_clsf: str | None = None, ovtm_mkt_clsf: str | None = None, inq_cnt: str | None = None) -> dict:
    """주식시간대별추이
    
    KB증권 API: IVU10080 (POST /api/v1/ivu10080)
    
    Args:
        excg_clsf: 거래소구분 (선택). 0:통합, 1:KRX, 2:NXT
        is_cd: 종목코드 (필수).
        ovtm_mkt_clsf: 시간외장구분 (선택). 0:정규장, 1:시간외
        inq_cnt: 조회건수 (선택).
    """
    body = {
        "excg_clsf": excg_clsf,
        "is_cd": is_cd,
        "ovtm_mkt_clsf": ovtm_mkt_clsf,
        "inq_cnt": inq_cnt,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivu10080", body)


@mcp.tool()
async def quote_kr_get_price(excg_clsf: str, shrt_cd: str) -> dict:
    """조회 시점의 주식 현재가를 조회 하는 API
    
    KB증권 API: IVU10140 (POST /api/v1/ivu10140)
    
    Args:
        excg_clsf: 거래소구분 (필수). 0:통합, 1:KRX, 2:NXT
        shrt_cd: 단축코드 (필수).
    """
    body = {
        "excg_clsf": excg_clsf,
        "shrt_cd": shrt_cd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivu10140", body)


@mcp.tool()
async def quote_kr_get_broker_trend(is_cd: str, excg_clsf: str | None = None) -> dict:
    """당일주요외국계거래원
    
    KB증권 API: IVU10420 (POST /api/v1/ivu10420)
    
    Args:
        excg_clsf: 거래소구분 (선택). 0:통합, 1:KRX, 2:NXT
        is_cd: 종목코드 (필수).
    """
    body = {
        "excg_clsf": excg_clsf,
        "is_cd": is_cd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivu10420", body)


@mcp.tool()
async def quote_kr_get_investor_trend(excg_clsf: str | None = None, is_cd: str | None = None, strt_dt: str | None = None, end_dt: str | None = None, amt_q_clsf: str | None = None, trd_clsf: str | None = None, acml_clsf: str | None = None) -> dict:
    """IVU10430 API 호출
    
    KB증권 API: IVU10430 (POST /api/v1/ivu10430)
    
    Args:
        excg_clsf: 거래소구분 (선택). 0:통합, 1:KRX, 2:NXT
        is_cd: 종목코드 (선택).
        strt_dt: 시작일자 (선택).
        end_dt: 종료일자 (선택).
        amt_q_clsf: 금액수량구분 (선택). 1:금액, 2:수량
        trd_clsf: 매매구분 (선택). 1:순매수, 2:매수, 3:매도
        acml_clsf: 누적구분 (선택). 0:누적안함, 1:누적
    """
    body = {
        "excg_clsf": excg_clsf,
        "is_cd": is_cd,
        "strt_dt": strt_dt,
        "end_dt": end_dt,
        "amt_q_clsf": amt_q_clsf,
        "trd_clsf": trd_clsf,
        "acml_clsf": acml_clsf,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivu10430", body)


@mcp.tool()
async def quote_kr_get_program_trading(excg_clsf: str | None = None, is_cd: str | None = None, amt_q_clsf: str | None = None, prd_clsf: str | None = None, inq_cnt: str | None = None) -> dict:
    """IVU10450 API 호출
    
    KB증권 API: IVU10450 (POST /api/v1/ivu10450)
    
    Args:
        excg_clsf: 거래소구분 (선택). 0:통합, 1:KRX, 2:NXT
        is_cd: 종목코드 (선택).
        amt_q_clsf: 금액수량구분 (선택). 금액수량구분 : 1:금액, 2:수량
        prd_clsf: 기간구분 (선택). 기간구분 : 1:시간별, 2:일별
        inq_cnt: 조회건수 (선택).
    """
    body = {
        "excg_clsf": excg_clsf,
        "is_cd": is_cd,
        "amt_q_clsf": amt_q_clsf,
        "prd_clsf": prd_clsf,
        "inq_cnt": inq_cnt,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivu10450", body)


@mcp.tool()
async def quote_kr_get_stock_info(stnd_is_cd: str) -> dict:
    """종목 기본 정보 조회 하는 APIinput 의 종목코드에 대한 정보를 단건 조회
    
    KB증권 API: SIQM4900 (POST /api/v1/siqm4900)
    
    Args:
        stnd_is_cd: 표준종목코드 (필수).
    """
    body = {
        "stnd_is_cd": stnd_is_cd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/siqm4900", body)


@mcp.tool()
async def quote_kr_get_market_status() -> dict:
    """SZQM0771 API 호출
    
    KB증권 API: SZQM0771 (POST /api/v1/szqm0771)
    """
    body: dict = {}
    return await call("/api/v1/szqm0771", body)


@mcp.tool()
async def quote_kr_get_company_overview(is_cd: str) -> dict:
    """종목의 간략한 기업 정보를 조회하는 API
    
    KB증권 API: IVM10050 (POST /api/v1/ivm10050)
    
    Args:
        is_cd: 종목코드 (필수).
    """
    body = {
        "is_cd": is_cd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivm10050", body)


@mcp.tool()
async def quote_kr_get_chart(info_ccd: str, mkt_clsf: str, chrt_clsf: str, is_cd: str, inq_clsf: str, minute_tck_indx: str | None = None, strt_dy: str | None = None, inq_cnt: str | None = None) -> dict:
    """통합차트
    
    KB증권 API: IVS11560 (POST /api/v1/ivs11560)
    
    Args:
        info_ccd: 정보구분코드 (필수). 1:원주가 2:수정주가(KOSPI, KOSDAQ 종목만)
        mkt_clsf: 시장구분 (필수). 0:KOSPI 1:KOSDAQ
        chrt_clsf: 차트구분 (필수). D:일별 W:주별 M:월별 Y:년별(주식) B:분봉 T:틱
        minute_tck_indx: MINUTE틱지수 (선택). 분, 틱, 일 선택시 조회 주기 표시
        is_cd: 종목코드 (필수).
        inq_clsf: 조회구분 (필수). 1:날짜로 조회 2:데이터수로 조회
        strt_dy: 시작일 (선택).
        inq_cnt: 조회건수 (선택).
    """
    body = {
        "info_ccd": info_ccd,
        "mkt_clsf": mkt_clsf,
        "chrt_clsf": chrt_clsf,
        "minute_tck_indx": minute_tck_indx,
        "is_cd": is_cd,
        "inq_clsf": inq_clsf,
        "strt_dy": strt_dy,
        "inq_cnt": inq_cnt,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivs11560", body)

