"""Generated by scripts/generate_tools.py — do not edit by hand.

Regenerate with: python scripts/generate_tools.py
Source: spec/kbsec_api_spec.json + spec/tool_metadata.yaml
"""
from app import mcp
from client import call


@mcp.tool()
async def order_kr_place_reserve_order(ordr_jb_clsf: str, is_cd: str, ordr_uprc: str, ordr_q: str, ordr_ccd: str, strt_dt: str | None = None, end_dt: str | None = None, mkt_tm_ccd: str | None = None) -> dict:
    """국내주식 예약 주문을 현금 및 신용 통합으로 접수합니다.정규 거래 시간 외에 다음 거래일에 실행될 주식 매수·매도 예약 주문을 사전에 등록할 수 있습니다.
    
    KB증권 API: SSAM0831 (POST /api/v1/ssam0831)
    
    Args:
        ordr_jb_clsf: 주문업무구분 (필수). 1:매도,2:매수
        is_cd: 종목코드 (필수).
        ordr_uprc: 주문단가 (필수).
        ordr_q: 주문수량 (필수).
        ordr_ccd: 주문구분코드 (필수). 00:지정가,03:시장가,12:최유리지정가,13:최우선지정가
        strt_dt: 시작일자 (선택).
        end_dt: 종료일자 (선택).
        mkt_tm_ccd: 시장시간구분코드 (선택).
    """
    body = {
        "ordr_jb_clsf": ordr_jb_clsf,
        "is_cd": is_cd,
        "ordr_uprc": ordr_uprc,
        "ordr_q": ordr_q,
        "ordr_ccd": ordr_ccd,
        "strt_dt": strt_dt,
        "end_dt": end_dt,
        "mkt_tm_ccd": mkt_tm_ccd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssam0831", body)


@mcp.tool()
async def order_kr_place_sell_order(mkt_tm_clsf: str, is_cd: str, ordr_q: str, ordr_uprc: str, ordr_ccd: str, sor_ordr_ccd: str | None = None) -> dict:
    """국내주식 현금 매도 주문을 접수합니다.시장가, 지정가 등 다양한 주문 유형을 지원하며, 보유 주식의 전부 또는 일부를 매도할 수 있습니다.
    
    KB증권 API: SSAM1801 (POST /api/v1/ssam1801)
    
    Args:
        mkt_tm_clsf: 시장시간구분 (필수). 1:정규장,2:장개시전시간외종가,3:장종료후시간외종가,4:장종료후시간외단일가
        is_cd: 종목코드 (필수).
        ordr_q: 주문수량 (필수).
        ordr_uprc: 주문단가 (필수).
        ordr_ccd: 주문구분코드 (필수). 00:지정가,03:시장가,12:최유리지정가,13:최우선지정가,M3:중간가
        sor_ordr_ccd: SOR주문구분코드 (선택). K:KRX,N:NXT,S:SOR
    """
    body = {
        "mkt_tm_clsf": mkt_tm_clsf,
        "is_cd": is_cd,
        "ordr_q": ordr_q,
        "ordr_uprc": ordr_uprc,
        "ordr_ccd": ordr_ccd,
        "sor_ordr_ccd": sor_ordr_ccd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssam1801", body)


@mcp.tool()
async def order_kr_place_buy_order(mkt_tm_clsf: str, is_cd: str, ordr_q: str, ordr_uprc: str, ordr_ccd: str, sor_ordr_ccd: str | None = None) -> dict:
    """국내주식 현금 매수 주문을 접수합니다.시장가, 지정가 등 다양한 주문 유형을 지원합니다. 스톱지정가 주문 시 ordr_ccd 값을 확인하세요.
    
    KB증권 API: SSAM1802 (POST /api/v1/ssam1802)
    
    Args:
        mkt_tm_clsf: 시장시간구분 (필수). 1:정규장,2:장개시전시간외종가,3:장종료후시간외종가,4:장종료후시간외단일가
        is_cd: 종목코드 (필수).
        ordr_q: 주문수량 (필수).
        ordr_uprc: 주문단가 (필수).
        ordr_ccd: 주문구분코드 (필수). 00:지정가,03:시장가,12:최유리지정가,13:최우선지정가, M3:중간가
        sor_ordr_ccd: SOR주문구분코드 (선택). K:KRX,N:NXT,S:SOR
    """
    body = {
        "mkt_tm_clsf": mkt_tm_clsf,
        "is_cd": is_cd,
        "ordr_q": ordr_q,
        "ordr_uprc": ordr_uprc,
        "ordr_ccd": ordr_ccd,
        "sor_ordr_ccd": sor_ordr_ccd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssam1802", body)


@mcp.tool()
async def order_kr_amend_order(mkt_tm_clsf: str, is_cd: str, ordr_q: str, ordr_uprc: str, ordr_ccd: str, crct_clsf: str, orgn_ordr_no: str, sor_ordr_ccd: str | None = None) -> dict:
    """미체결 상태의 국내주식 주문을 정정합니다.원주문번호와 정정할 수량·가격을 입력하여 미체결 주문의 내용을 변경할 수 있습니다.
    
    KB증권 API: SSAM1805 (POST /api/v1/ssam1805)
    
    Args:
        mkt_tm_clsf: 시장시간구분 (필수). 1:정규장,2:장개시전시간외종가,3:장종료후시간외종가,4:장종료후시간외단일가
        is_cd: 종목코드 (필수).
        ordr_q: 주문수량 (필수). *일부정정시 입력
        ordr_uprc: 주문단가 (필수).
        ordr_ccd: 주문구분코드 (필수). 00:지정가,03:시장가,05:조건부지정가,12:최유리지정가,13:최우선지정가
        crct_clsf: 정정구분 (필수). 1:일부정정,2:전부정정
        orgn_ordr_no: 원주문번호 (필수).
        sor_ordr_ccd: SOR주문구분코드 (선택). K:KRX,N:NXT,S:SOR
    """
    body = {
        "mkt_tm_clsf": mkt_tm_clsf,
        "is_cd": is_cd,
        "ordr_q": ordr_q,
        "ordr_uprc": ordr_uprc,
        "ordr_ccd": ordr_ccd,
        "crct_clsf": crct_clsf,
        "orgn_ordr_no": orgn_ordr_no,
        "sor_ordr_ccd": sor_ordr_ccd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssam1805", body)


@mcp.tool()
async def order_kr_cancel_order(is_cd: str, crct_clsf: str, orgn_ordr_no: str, ordr_q: str | None = None) -> dict:
    """취소주문
    
    KB증권 API: SSAM1806 (POST /api/v1/ssam1806)
    
    Args:
        is_cd: 종목코드 (필수).
        ordr_q: 주문수량 (선택).
        crct_clsf: 정정구분 (필수). 1:일부정정,2:전부정정
        orgn_ordr_no: 원주문번호 (필수).
    """
    body = {
        "is_cd": is_cd,
        "ordr_q": ordr_q,
        "crct_clsf": crct_clsf,
        "orgn_ordr_no": orgn_ordr_no,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssam1806", body)


@mcp.tool()
async def order_kr_place_fractional_sell_order(is_cd: str, ordr_amt: str, dcml_ordr_std_ccd: str, tv_s_est_f: str, ordr_q_p6: str | None = None) -> dict:
    """국내주식 소수점 단위 매도 주문을 접수합니다.1주 미만의 소수점 단위로 보유한 주식을 매도할 수 있습니다.
    
    KB증권 API: SSAM5762 (POST /api/v1/ssam5762)
    
    Args:
        is_cd: 종목코드 (필수).
        ordr_q_p6: 주문수량P6 (선택).
        ordr_amt: 주문금액 (필수).
        dcml_ordr_std_ccd: 소수점주문기준구분코드 (필수). 1:금액, 2:수량 (전량일때 2번으로)
        tv_s_est_f: 전량매도설정여부 (필수). 0:일부매도, 1:전량매도
    """
    body = {
        "is_cd": is_cd,
        "ordr_q_p6": ordr_q_p6,
        "ordr_amt": ordr_amt,
        "dcml_ordr_std_ccd": dcml_ordr_std_ccd,
        "tv_s_est_f": tv_s_est_f,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssam5762", body)


@mcp.tool()
async def order_kr_place_fractional_buy_order(is_cd: str, ordr_amt: str, dcml_ordr_std_ccd: str, ordr_q_p6: str | None = None) -> dict:
    """소수점 매수주문
    
    KB증권 API: SSAM5763 (POST /api/v1/ssam5763)
    
    Args:
        is_cd: 종목코드 (필수).
        ordr_q_p6: 주문수량P6 (선택).
        ordr_amt: 주문금액 (필수).
        dcml_ordr_std_ccd: 소수점주문기준구분코드 (필수). 1:금액,2:수량
    """
    body = {
        "is_cd": is_cd,
        "ordr_q_p6": ordr_q_p6,
        "ordr_amt": ordr_amt,
        "dcml_ordr_std_ccd": dcml_ordr_std_ccd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssam5763", body)


@mcp.tool()
async def order_kr_cancel_fractional_order(dmstc_stk_dcml_trd_jb_ccd: str, ordr_sqc: str, ordr_dt: str, bnf_is_cd: str, trd_dl_ccd: str, dmstc_stk_dcml_ordr_sq: str) -> dict:
    """소수점 주문취소
    
    KB증권 API: SSAM5764 (POST /api/v1/ssam5764)
    
    Args:
        dmstc_stk_dcml_trd_jb_ccd: 국내주식소수점매매업무구분코드 (필수). 01:일반,02:자기,03:정기매수,04:비상장분할 일괄청산,05:정리매매 일괄청산
        ordr_sqc: 주문회차 (필수).
        ordr_dt: 주문일자 (필수).
        bnf_is_cd: 수익증권종목코드 (필수).
        trd_dl_ccd: 매매거래구분코드 (필수). 01:매도, 02:매수
        dmstc_stk_dcml_ordr_sq: 국내주식소수점주문일련번호 (필수). SSQM5765 api 의 acpt_no 값
    """
    body = {
        "dmstc_stk_dcml_trd_jb_ccd": dmstc_stk_dcml_trd_jb_ccd,
        "ordr_sqc": ordr_sqc,
        "ordr_dt": ordr_dt,
        "bnf_is_cd": bnf_is_cd,
        "trd_dl_ccd": trd_dl_ccd,
        "dmstc_stk_dcml_ordr_sq": dmstc_stk_dcml_ordr_sq,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssam5764", body)


@mcp.tool()
async def order_kr_get_buyable_amount(is_no: str | None = None) -> dict:
    """특정 종목에 대해 현재 계좌에서 매수 가능한 금액과 수량을 조회합니다. 주문 전 희망 매수 단가를 입력하면 해당 단가 기준의 최대 매수 가능 수량을 미리 확인할 수 있습니다.
    
    KB증권 API: SSQM1802 (POST /api/v1/ssqm1802)
    
    Args:
        is_no: 종목번호 (선택).
    """
    body = {
        "is_no": is_no,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ssqm1802", body)

