"""Generated by scripts/generate_tools.py — do not edit by hand.

Regenerate with: python scripts/generate_tools.py
Source: spec/kbsec_api_spec.json + spec/tool_metadata.yaml
"""
from app import mcp
from client import call


@mcp.tool()
async def ranking_kr_get_top_trading_value(excg_clsf: str | None = None, mkt_clsf: str | None = None, thdy_bdy_clsf: str | None = None, inq_cnt: str | None = None, srt_clsf: str | None = None) -> dict:
    """ATS통합-거래대금상위
    
    KB증권 API: IVU10210 (POST /api/v1/ivu10210)
    
    Args:
        excg_clsf: 거래소구분 (선택). 0:통합, 1:KRX, 2:NXT
        mkt_clsf: 시장구분 (선택). 1:전체, 2:KOSPI, 3:KOSDAQ
        thdy_bdy_clsf: 당일전일구분 (선택). 1:당일, 2:전일
        inq_cnt: 조회건수 (선택).
        srt_clsf: 정렬구분 (선택). 1:상위, 2:하위
    """
    body = {
        "excg_clsf": excg_clsf,
        "mkt_clsf": mkt_clsf,
        "thdy_bdy_clsf": thdy_bdy_clsf,
        "inq_cnt": inq_cnt,
        "srt_clsf": srt_clsf,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivu10210", body)


@mcp.tool()
async def ranking_kr_get_top_change_rate(excg_clsf: str | None = None, mkt_clsf: str | None = None, inq_cnt: str | None = None, srt_clsf: str | None = None) -> dict:
    """ATS통합-전일대비등락율상위
    
    KB증권 API: IVU10240 (POST /api/v1/ivu10240)
    
    Args:
        excg_clsf: 거래소구분 (선택). 0:통합, 1:KRX, 2:NXT
        mkt_clsf: 시장구분 (선택). 1:전체, 2:KOSPI, 3:KOSDAQ, 4:KOSPI200, 5:KOSDAQ150
        inq_cnt: 조회건수 (선택).
        srt_clsf: 정렬구분 (선택). 1:상승율, 2:하락율, 3:상승폭, 4:하락폭
    """
    body = {
        "excg_clsf": excg_clsf,
        "mkt_clsf": mkt_clsf,
        "inq_cnt": inq_cnt,
        "srt_clsf": srt_clsf,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivu10240", body)


@mcp.tool()
async def ranking_kr_get_top_price_surge_drop(excg_clsf: str | None = None, mkt_clsf: str | None = None, inq_cnt: str | None = None, up_dwn_ccd: str | None = None, minute_dy_ccd: str | None = None, minute_dy_unt: str | None = None) -> dict:
    """ATS통합-가격급등/급락종목
    
    KB증권 API: IVU10270 (POST /api/v1/ivu10270)
    
    Args:
        excg_clsf: 거래소구분 (선택). 0:통합, 1:KRX, 2:NXT
        mkt_clsf: 시장구분 (선택). 1:전체, 2:KOSPI, 3:KOSDAQ
        inq_cnt: 조회건수 (선택).
        up_dwn_ccd: 등락구분코드 (선택). 1:급등, 2:급락
        minute_dy_ccd: MINUTE일구분코드 (선택). 1:분전, 2:일전
        minute_dy_unt: MINUTE일단위 (선택).
    """
    body = {
        "excg_clsf": excg_clsf,
        "mkt_clsf": mkt_clsf,
        "inq_cnt": inq_cnt,
        "up_dwn_ccd": up_dwn_ccd,
        "minute_dy_ccd": minute_dy_ccd,
        "minute_dy_unt": minute_dy_unt,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivu10270", body)


@mcp.tool()
async def ranking_kr_get_top_volume(excg_clsf: str | None = None, mkt_clsf: str | None = None) -> dict:
    """ATS통합-당일거래량상위
    
    KB증권 API: IVU10280 (POST /api/v1/ivu10280)
    
    Args:
        excg_clsf: 거래소구분 (선택). 0:통합, 1:KRX, 2:NXT
        mkt_clsf: 시장구분 (선택). 시장구분 : 1:전체, 2:KOSPI, 3:KOSDAQ
    """
    body = {
        "excg_clsf": excg_clsf,
        "mkt_clsf": mkt_clsf,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivu10280", body)


@mcp.tool()
async def ranking_kr_get_new_high_low(excg_clsf: str | None = None, mkt_clsf: str | None = None, inq_cnt: str | None = None, nw_stk_lw_ccd: str | None = None, std_clsf: str | None = None, prd_clsf: str | None = None, excd_clsf: str | None = None) -> dict:
    """신고가/신저가(IVU10550)
    
    KB증권 API: IVU10550 (POST /api/v1/ivu10550)
    
    Args:
        excg_clsf: 거래소구분 (선택). 0:통합, 1:KRX, 2:NXT
        mkt_clsf: 시장구분 (선택). 1:전체, 2:KOSPI, 3:KOSDAQ
        inq_cnt: 조회건수 (선택).
        nw_stk_lw_ccd: 신고저구분코드 (선택). : 1:신고가, 2:신저가
        std_clsf: 기준구분 (선택). 1:고저기준, 2:종가기준
        prd_clsf: 기간구분 (선택). 1:전일 2:5일 3:10일 4:20일 5:60일 6:250일 7:120일
        excd_clsf: 돌파구분 (선택). 1:일시돌파, 2:돌파유지
    """
    body = {
        "excg_clsf": excg_clsf,
        "mkt_clsf": mkt_clsf,
        "inq_cnt": inq_cnt,
        "nw_stk_lw_ccd": nw_stk_lw_ccd,
        "std_clsf": std_clsf,
        "prd_clsf": prd_clsf,
        "excd_clsf": excd_clsf,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivu10550", body)


@mcp.tool()
async def ranking_kr_get_top_open_price_change(mkt_clsf: str | None = None, inq_cnt: str | None = None, srt_clsf: str | None = None) -> dict:
    """시가대비등락율상위(IVS10910)
    
    KB증권 API: IVS10910 (POST /api/v1/ivs10910)
    
    Args:
        mkt_clsf: 시장구분 (선택). 1:전체, 2:KOSPI, 3:KOSDAQ, 4:KOSPI200, 5:KOSDAQ150
        inq_cnt: 조회건수 (선택).
        srt_clsf: 정렬구분 (선택). 1:상승, 2:하락
    """
    body = {
        "mkt_clsf": mkt_clsf,
        "inq_cnt": inq_cnt,
        "srt_clsf": srt_clsf,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivs10910", body)


@mcp.tool()
async def ranking_kr_get_top_market_cap(inq_cnt: str | None = None) -> dict:
    """시가총액상위
    
    KB증권 API: IVS10920 (POST /api/v1/ivs10920)
    
    Args:
        inq_cnt: 조회건수 (선택).
    """
    body = {
        "inq_cnt": inq_cnt,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivs10920", body)


@mcp.tool()
async def ranking_kr_get_top_after_hours_change(mkt_clsf: str | None = None, srt_clsf: str | None = None, thdy_bdy_clsf: str | None = None, inq_cnt: str | None = None) -> dict:
    """시간외단일가등락율순위(IVS11190)
    
    KB증권 API: IVS11190 (POST /api/v1/ivs11190)
    
    Args:
        mkt_clsf: 시장구분 (선택). 1:전체, 2:거래소, 3:코스닥
        srt_clsf: 정렬구분 (선택). 1:상승율, 2:하락율
        thdy_bdy_clsf: 당일전일구분 (선택). 1:당일, 2:전일
        inq_cnt: 조회건수 (선택).
    """
    body = {
        "mkt_clsf": mkt_clsf,
        "srt_clsf": srt_clsf,
        "thdy_bdy_clsf": thdy_bdy_clsf,
        "inq_cnt": inq_cnt,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivs11190", body)


@mcp.tool()
async def ranking_kr_get_top_foreign_institution_trading(excg_clsf: str | None = None, mkt_clsf: str | None = None, invstr_ccd: str | None = None, prd_clsf: str | None = None, rnk_clsf: str | None = None) -> dict:
    """외국인기관매매상위
    
    KB증권 API: IVU10020 (POST /api/v1/ivu10020)
    
    Args:
        excg_clsf: 거래소구분 (선택). 0:통합, 1:KRX, 2:NXT
        mkt_clsf: 시장구분 (선택). 0:거래소, 1:코스닥, 2:전체
        invstr_ccd: 투자자구분코드 (선택). 0:외국인 1:기관 2:외국인+기관 3:증권 4:보험 5:투신 6:사모펀드 7:은행 8:종금 9:기금 A:기타 B:국가지자체 C:개인 D:기타외국인
        prd_clsf: 기간구분 (선택). 0:전일 1:1주 2:1달 3:3달 4:6달 5:1년 6:연초
        rnk_clsf: 순위구분 (선택). 0:순매수 1:순매도 2:지분증가 3:지분감소 4:연속순매수 5:연속순매도
    """
    body = {
        "excg_clsf": excg_clsf,
        "mkt_clsf": mkt_clsf,
        "invstr_ccd": invstr_ccd,
        "prd_clsf": prd_clsf,
        "rnk_clsf": rnk_clsf,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/ivu10020", body)

