"""Generated by scripts/generate_tools.py — do not edit by hand.

Regenerate with: python scripts/generate_tools.py
Source: spec/kbsec_api_spec.json + spec/tool_metadata.yaml
"""
from app import mcp
from client import call


@mcp.tool()
async def orderhist_os_get_execution_history(ccls_clsf: str, ordr_dt: str | None = None, dl_clsf: str | None = None, nxt_key: str | None = None) -> dict:
    """해외주식 주문 체결 내역을 조회합니다.지정된 기간 내 체결된 해외주식 주문의 종목, 매매 구분, 수량, 단가, 수수료 등을 확인할 수 있습니다.
    
    KB증권 API: SPQM2103 (POST /api/v1/spqm2103)
    
    Args:
        ccls_clsf: 체결구분 (필수). 1:전체,2:체결,3:미체결
        ordr_dt: 주문일자 (선택).
        dl_clsf: 거래구분 (선택). 0.전체 1.일반 2.소수점
        nxt_key: 다음키 (선택).
    """
    body = {
        "ccls_clsf": ccls_clsf,
        "ordr_dt": ordr_dt,
        "dl_clsf": dl_clsf,
        "nxt_key": nxt_key,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/spqm2103", body)


@mcp.tool()
async def orderhist_os_get_execution_status(strt_ordr_dt: str, end_ordr_dt: str, ccls_clsf: str, trd_clsf: str, stnd_is_cd: str | None = None, dl_clsf: str | None = None, nxt_key: str | None = None) -> dict:
    """해외주식 주문 체결 현황을 조회합니다.당일 접수한 해외주식 주문의 체결 수량, 미체결 수량, 체결 단가 등 처리 상태를 확인할 수 있습니다.
    
    KB증권 API: SPQM2204 (POST /api/v1/spqm2204)
    
    Args:
        strt_ordr_dt: 시작주문일자 (필수).
        end_ordr_dt: 종료주문일자 (필수).
        ccls_clsf: 체결구분 (필수). 0: 전체, 1: 체결, 2: 미체결
        trd_clsf: 매매구분 (필수). 99: 전체, 01: 매도, 02: 매수
        stnd_is_cd: 표준종목코드 (선택).
        dl_clsf: 거래구분 (선택). 0:전체 ,1:일반거래,2:소수점거래
        nxt_key: 다음키 (선택).
    """
    body = {
        "strt_ordr_dt": strt_ordr_dt,
        "end_ordr_dt": end_ordr_dt,
        "ccls_clsf": ccls_clsf,
        "trd_clsf": trd_clsf,
        "stnd_is_cd": stnd_is_cd,
        "dl_clsf": dl_clsf,
        "nxt_key": nxt_key,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/spqm2204", body)


@mcp.tool()
async def orderhist_os_get_reserve_order_list(rsrv_dt: str | None = None, stnd_is_cd: str | None = None, trd_clsf: str | None = None, krw_unty_mgn_rqst_f: str | None = None, cn_key: str | None = None) -> dict:
    """해외주식 예약주문조회
    
    KB증권 API: SPQO2105 (POST /api/v1/spqo2105)
    
    Args:
        rsrv_dt: 예약일자 (선택).
        stnd_is_cd: 표준종목코드 (선택).
        trd_clsf: 매매구분 (선택). 1:시장가,3:지정가
        krw_unty_mgn_rqst_f: 원화통합증거금신청여부 (선택). 0: 외화, 1: 원화
        cn_key: 연속키 (선택).
    """
    body = {
        "rsrv_dt": rsrv_dt,
        "stnd_is_cd": stnd_is_cd,
        "trd_clsf": trd_clsf,
        "krw_unty_mgn_rqst_f": krw_unty_mgn_rqst_f,
        "cn_key": cn_key,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/spqo2105", body)

