"""Generated by scripts/generate_tools.py — do not edit by hand.

Regenerate with: python scripts/generate_tools.py
Source: spec/kbsec_api_spec.json + spec/tool_metadata.yaml
"""
from app import mcp
from client import call


@mcp.tool()
async def order_os_get_buyable_amount(stnd_is_cd: str) -> dict:
    """해외주식 글로벌원마켓 서비스에서 통화별 주문 가능 금액을 조회합니다.해외주식 매수 주문 전 통화별로 사용 가능한 주문 가능 금액을 확인할 수 있습니다.
    
    KB증권 API: SKQM2106 (POST /api/v1/skqm2106)
    
    Args:
        stnd_is_cd: 표준종목코드 (필수).
    """
    body = {
        "stnd_is_cd": stnd_is_cd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/skqm2106", body)


@mcp.tool()
async def order_os_get_buyable_amount_status() -> dict:
    """해외주식 글로벌원마켓 서비스에서 통화별 주문 가능 예수금 현황을 조회합니다. 미국 달러, 홍콩 달러 등 통화별로 보유 중인 외화 예수금 및 주문 가능 금액 현황을 확인할 수 있습니다.
    
    KB증권 API: SKQM3350 (POST /api/v1/skqm3350)
    """
    body: dict = {}
    return await call("/api/v1/skqm3350", body)


@mcp.tool()
async def order_os_place_order(trd_dl_ccd: str, is_cd: str, frgn_ordr_typ_cd: str, frgn_ordr_q: str, frgn_ordr_prc_p4: str) -> dict:
    """해외주식 매도 또는 매수 주문을 접수합니다.미국, 홍콩, 일본 등 글로벌원마켓 지원 거래소의 주식을 시장가 또는 지정가로 주문할 수 있습니다.
    
    KB증권 API: SKAM2101 (POST /api/v1/skam2101)
    
    Args:
        trd_dl_ccd: 매매거래구분코드 (필수). 01:매도, 02:매수
        is_cd: 종목코드 (필수). ex)TSLA
        frgn_ordr_typ_cd: 해외주문유형코드 (필수). 1:시장가, 2:지정가, 3:VWAP시장가, 4:TWAP시장가
        frgn_ordr_q: 해외주문수량 (필수).
        frgn_ordr_prc_p4: 해외주문가격P4 (필수).
    """
    body = {
        "trd_dl_ccd": trd_dl_ccd,
        "is_cd": is_cd,
        "frgn_ordr_typ_cd": frgn_ordr_typ_cd,
        "frgn_ordr_q": frgn_ordr_q,
        "frgn_ordr_prc_p4": frgn_ordr_prc_p4,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/skam2101", body)


@mcp.tool()
async def order_os_amend_cancel_order(crct_cncl_clsf: str, is_cd: str, orgn_ordr_no: str, frgn_ordr_prc_p4: str) -> dict:
    """접수된 해외주식 주문을 정정하거나 취소합니다.미체결 상태의 해외주식 주문에 대해 수량·가격 정정 또는 주문 취소를 요청할 수 있습니다.
    
    KB증권 API: SKAM2102 (POST /api/v1/skam2102)
    
    Args:
        crct_cncl_clsf: 정정취소구분 (필수). 1:정정, 2:취소
        is_cd: 종목코드 (필수).
        orgn_ordr_no: 원주문번호 (필수).
        frgn_ordr_prc_p4: 해외주문가격P4 (필수).
    """
    body = {
        "crct_cncl_clsf": crct_cncl_clsf,
        "is_cd": is_cd,
        "orgn_ordr_no": orgn_ordr_no,
        "frgn_ordr_prc_p4": frgn_ordr_prc_p4,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/skam2102", body)


@mcp.tool()
async def order_os_get_fractional_buyable_amount() -> dict:
    """해외주식 소수점 매매 시 주문 가능 금액을 조회합니다.소수점 단위로 매수하려는 해외주식 종목과 금액을 입력하면 주문 가능 여부를 확인할 수 있습니다.
    
    KB증권 API: SPQN5472 (POST /api/v1/spqn5472)
    """
    body: dict = {}
    return await call("/api/v1/spqn5472", body)


@mcp.tool()
async def order_os_place_fractional_order(trd_dl_ccd: str, is_cd: str, amt_q_clsf: str, frgn_ordr_typ_cd: str, ordr_amt: str, tv_s_est_f: str | None = None, crncy_ccd: str | None = None, dcml_ordr_q_p6: str | None = None, frgn_ordr_prc_p4: str | None = None) -> dict:
    """해외주식 소수점 단위 매도 또는 매수 주문을 접수합니다.1주 미만의 소수점 단위로 해외주식을 거래할 수 있어 소액으로도 해외 우량주에 투자할 수 있습니다.
    
    KB증권 API: SKAM2201 (POST /api/v1/skam2201)
    
    Args:
        trd_dl_ccd: 매매거래구분코드 (필수). 01-매도, 02-매수
        is_cd: 종목코드 (필수).
        amt_q_clsf: 금액수량구분 (필수). 0-금액, 1-수량
        tv_s_est_f: 전량매도설정여부 (선택). 0-일부매도, 1-전량매도
        frgn_ordr_typ_cd: 해외주문유형코드 (필수). 2-지정가, E-유사시장가
        crncy_ccd: 통화구분코드 (선택). 0-원화, 1-외화(USD)
        ordr_amt: 주문금액 (필수).
        dcml_ordr_q_p6: 소수점주문수량P6 (선택).
        frgn_ordr_prc_p4: 해외주문가격P4 (선택).
    """
    body = {
        "trd_dl_ccd": trd_dl_ccd,
        "is_cd": is_cd,
        "amt_q_clsf": amt_q_clsf,
        "tv_s_est_f": tv_s_est_f,
        "frgn_ordr_typ_cd": frgn_ordr_typ_cd,
        "crncy_ccd": crncy_ccd,
        "ordr_amt": ordr_amt,
        "dcml_ordr_q_p6": dcml_ordr_q_p6,
        "frgn_ordr_prc_p4": frgn_ordr_prc_p4,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/skam2201", body)


@mcp.tool()
async def order_os_cancel_fractional_order(orgn_ordr_no: str) -> dict:
    """접수된 해외주식 소수점 주문을 취소합니다.미체결 상태의 해외주식 소수점 매수·매도 주문의 수량·가격을 변경하거나 취소할 수 있습니다.
    
    KB증권 API: SKAM2202 (POST /api/v1/skam2202)
    
    Args:
        orgn_ordr_no: 원주문번호 (필수).
    """
    body = {
        "orgn_ordr_no": orgn_ordr_no,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/skam2202", body)


@mcp.tool()
async def order_os_place_us_reserve_order(is_cd: str, trd_dl_ccd: str, ordr_typ_cd: str, ordr_q: str, frgn_ordr_prc_p4: str, strt_tm: str | None = None, end_tm: str | None = None) -> dict:
    """미국 주식에 대한 예약 주문을 접수합니다.정규 거래 시간 외에도 다음 거래일 시장 개장 시 자동으로 실행될 미국 주식 주문을 사전 접수합니다.
    
    KB증권 API: SPAO2104 (POST /api/v1/spao2104)
    
    Args:
        is_cd: 종목코드 (필수).
        trd_dl_ccd: 매매거래구분코드 (필수). 01:매도,02:매수
        ordr_typ_cd: 주문유형코드 (필수). 1:시장가, 2:지정가, 3:VWAP시장가, 4:TWAP시장가
        ordr_q: 주문수량 (필수).
        frgn_ordr_prc_p4: 해외주문가격P4 (필수).
        strt_tm: 시작시간 (선택).
        end_tm: 종료시간 (선택).
    """
    body = {
        "is_cd": is_cd,
        "trd_dl_ccd": trd_dl_ccd,
        "ordr_typ_cd": ordr_typ_cd,
        "ordr_q": ordr_q,
        "frgn_ordr_prc_p4": frgn_ordr_prc_p4,
        "strt_tm": strt_tm,
        "end_tm": end_tm,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/spao2104", body)


@mcp.tool()
async def order_os_cancel_us_reserve_order(is_cd: str, cncl_ordr_no: str, trd_clsf: str | None = None, ordr_typ: str | None = None, ordr_q: str | None = None, frgn_ordr_prc_p4: str | None = None) -> dict:
    """접수된 미국 주식 예약 주문을 취소합니다.아직 처리되지 않은 미국 주식 예약 주문을 취소 처리합니다.
    
    KB증권 API: SPAO2106 (POST /api/v1/spao2106)
    
    Args:
        is_cd: 종목코드 (필수).
        trd_clsf: 매매구분 (선택).
        ordr_typ: 주문유형 (선택).
        ordr_q: 주문수량 (선택).
        frgn_ordr_prc_p4: 해외주문가격P4 (선택).
        cncl_ordr_no: 취소주문번호 (필수).
    """
    body = {
        "is_cd": is_cd,
        "trd_clsf": trd_clsf,
        "ordr_typ": ordr_typ,
        "ordr_q": ordr_q,
        "frgn_ordr_prc_p4": frgn_ordr_prc_p4,
        "cncl_ordr_no": cncl_ordr_no,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/spao2106", body)

