"""Generated by scripts/generate_tools.py — do not edit by hand.

Regenerate with: python scripts/generate_tools.py
Source: spec/kbsec_api_spec.json + spec/tool_metadata.yaml
"""
from app import mcp
from client import call


@mcp.tool()
async def quote_os_get_stock_info(Record1: list[dict] | None = None) -> dict:
    """해외주식 종목 정보를 조회할 수 있는 API 입니다.
    
    KB증권 API: SIAM4983 (POST /api/v1/siam4983)
    
    Args:
        Record1: Record1 (선택).
    """
    body = {
        "Record1": Record1,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/siam4983", body)


@mcp.tool()
async def quote_os_get_price(krx_cd: str, is_cd: str) -> dict:
    """현재가
    
    KB증권 API: GSS10030 (POST /api/v1/gss10030)
    
    Args:
        krx_cd: 거래소코드 (필수). NAS: 나스닥, NYS: 뉴욕거래소, AMX: 아멕스
        is_cd: 종목코드 (필수).
    """
    body = {
        "krx_cd": krx_cd,
        "is_cd": is_cd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/gss10030", body)


@mcp.tool()
async def quote_os_get_orderbook(krx_cd: str, is_cd: str) -> dict:
    """호가
    
    KB증권 API: GSS10040 (POST /api/v1/gss10040)
    
    Args:
        krx_cd: 거래소코드 (필수). NAS: 나스닥, NYS: 뉴욕거래소, AMX: 아멕스
        is_cd: 종목코드 (필수).
    """
    body = {
        "krx_cd": krx_cd,
        "is_cd": is_cd,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/gss10040", body)


@mcp.tool()
async def quote_os_get_time_trades(krx_cd: str, is_cd: str, rcrd_c: str | None = None) -> dict:
    """시간대별체결
    
    KB증권 API: GSA10020 (POST /api/v1/gsa10020)
    
    Args:
        krx_cd: 거래소코드 KRX_CD (필수). NAS: 나스닥, NYS: 뉴욕거래소, AMX: 아멕스
        is_cd: 종목코드 IS_CD (필수).
        rcrd_c: 레코드수 RCRD_C (선택).
    """
    body = {
        "krx_cd": krx_cd,
        "is_cd": is_cd,
        "rcrd_c": rcrd_c,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/gsa10020", body)


@mcp.tool()
async def quote_os_get_chart(krx_cd: str, is_cd: str, chrt_clsf: str, bndl: str | None = None, mdfy_stk_prc_use_f: str | None = None, rcrd_c: str | None = None, srch_strt_dy: str | None = None, clsf: str | None = None) -> dict:
    """차트
    
    KB증권 API: GSC10060 (POST /api/v1/gsc10060)
    
    Args:
        krx_cd: 거래소코드 KRX_CD (필수).
        is_cd: 종목코드 IS_CD (필수).
        chrt_clsf: 차트구분 CHRT_CLSF (필수). 1:틱 2:분 3:일 4:주 5:월 6:년
        bndl: 묶음 BNDL (선택). 묶음틱 개수
        mdfy_stk_prc_use_f: 수정주가사용여부 MDFY_STK_PRC_USE_F (선택). 0:수정주가 미사용 1:수정주가사용
        rcrd_c: 레코드수 RCRD_C (선택). 최대요청개수:5000
        srch_strt_dy: 검색시작일 SRCH_STRT_DY (선택). 과거일자 검색용
        clsf: 구분 CLSF (선택).
    """
    body = {
        "krx_cd": krx_cd,
        "is_cd": is_cd,
        "chrt_clsf": chrt_clsf,
        "bndl": bndl,
        "mdfy_stk_prc_use_f": mdfy_stk_prc_use_f,
        "rcrd_c": rcrd_c,
        "srch_strt_dy": srch_strt_dy,
        "clsf": clsf,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/gsc10060", body)

