"""Generated by scripts/generate_tools.py — do not edit by hand.

Regenerate with: python scripts/generate_tools.py
Source: spec/kbsec_api_spec.json + spec/tool_metadata.yaml
"""
from app import mcp
from client import call


@mcp.tool()
async def account_os_get_settlement_status(strt_ordr_dt: str, end_ordr_dt: str, trd_clsf: str, stnd_is_cd: str | None = None, krw_unty_mgn_rqst_f: str | None = None, dl_clsf: str | None = None, nxt_key: str | None = None) -> dict:
    """해외주식 매매가 정산 현황을 조회합니다.체결된 해외주식 거래의 매매 단가 기준 정산 금액과 외화·원화 환산 내역을 확인할 수 있습니다.
    
    KB증권 API: SPQM2205 (POST /api/v1/spqm2205)
    
    Args:
        strt_ordr_dt: 시작주문일자 (필수).
        end_ordr_dt: 종료주문일자 (필수).
        trd_clsf: 매매구분 (필수). 99:전체, 01:매도, 02:매수
        stnd_is_cd: 표준종목코드 (선택).
        krw_unty_mgn_rqst_f: 원화통합증거금신청여부 (선택). 0: 외화기준, 1: 원화기준
        dl_clsf: 거래구분 (선택). 0:전체, 1:일반거래, 2:소수점거래
        nxt_key: 다음키 (선택).
    """
    body = {
        "strt_ordr_dt": strt_ordr_dt,
        "end_ordr_dt": end_ordr_dt,
        "trd_clsf": trd_clsf,
        "stnd_is_cd": stnd_is_cd,
        "krw_unty_mgn_rqst_f": krw_unty_mgn_rqst_f,
        "dl_clsf": dl_clsf,
        "nxt_key": nxt_key,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/spqm2205", body)


@mcp.tool()
async def account_os_get_daily_profit_loss(ordr_dt: str, stnd_is_cd: str | None = None, std_crncy_f: str | None = None, exch_r_aplc_f: str | None = None, frgn_stk_mgn_ccd: str | None = None, dl_clsf: str | None = None, nxt_key: str | None = None) -> dict:
    """당일 해외주식 매매 손익을 조회합니다.오늘 체결된 해외주식 거래에 대한 실현 손익, 수수료, 제세금을 통화별로 확인할 수 있습니다.
    
    KB증권 API: SPQM2206 (POST /api/v1/spqm2206)
    
    Args:
        ordr_dt: 주문일자 (필수).
        stnd_is_cd: 표준종목코드 (선택).
        std_crncy_f: 기준통화여부 (선택). 1:외화기준,2:원화기준
        exch_r_aplc_f: 환율적용여부 (선택). 1:환전시매도환율, 2:매매기준율
        frgn_stk_mgn_ccd: 해외주식증거금구분코드 (선택). 1:원화, 2:외화
        dl_clsf: 거래구분 (선택). 0:전체,1:일반거래,2:소수점거래
        nxt_key: 다음키 (선택).
    """
    body = {
        "ordr_dt": ordr_dt,
        "stnd_is_cd": stnd_is_cd,
        "std_crncy_f": std_crncy_f,
        "exch_r_aplc_f": exch_r_aplc_f,
        "frgn_stk_mgn_ccd": frgn_stk_mgn_ccd,
        "dl_clsf": dl_clsf,
        "nxt_key": nxt_key,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/spqm2206", body)


@mcp.tool()
async def account_os_get_period_profit_loss(strt_ordr_dt: str, end_ordr_dt: str, stnd_is_cd: str | None = None, std_crncy_f: str | None = None, exch_r_aplc_f: str | None = None, frgn_stk_mgn_ccd: str | None = None, dl_clsf: str | None = None, nxt_key: str | None = None) -> dict:
    """지정된 기간 동안의 해외주식 매매 손익을 조회합니다.기간 내 해외주식 거래의 실현 손익, 수수료, 세금을 종목별·통화별로 확인할 수 있습니다.
    
    KB증권 API: SPQM2207 (POST /api/v1/spqm2207)
    
    Args:
        strt_ordr_dt: 시작주문일자 (필수).
        end_ordr_dt: 종료주문일자 (필수).
        stnd_is_cd: 표준종목코드 (선택).
        std_crncy_f: 기준통화여부 (선택). 1:외화기준,2:원화기준
        exch_r_aplc_f: 환율적용여부 (선택). 1:환전시매도환율, 2:매매기준율
        frgn_stk_mgn_ccd: 해외주식증거금구분코드 (선택). 1:원화, 2:외화
        dl_clsf: 거래구분 (선택).
        nxt_key: 다음키 (선택).
    """
    body = {
        "strt_ordr_dt": strt_ordr_dt,
        "end_ordr_dt": end_ordr_dt,
        "stnd_is_cd": stnd_is_cd,
        "std_crncy_f": std_crncy_f,
        "exch_r_aplc_f": exch_r_aplc_f,
        "frgn_stk_mgn_ccd": frgn_stk_mgn_ccd,
        "dl_clsf": dl_clsf,
        "nxt_key": nxt_key,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/spqm2207", body)


@mcp.tool()
async def account_os_get_margin() -> dict:
    """글로벌원마켓(통합증거금) 서비스에 가입된 계좌의 증거금 사용 현황을 조회합니다. 국내·해외주식 통합 증거금 기준의 사용 가능 증거금과 현재 사용 중인 증거금을 확인할 수 있습니다.
    
    KB증권 API: SPQM3390 (POST /api/v1/spqm3390)
    """
    body: dict = {}
    return await call("/api/v1/spqm3390", body)


@mcp.tool()
async def account_os_get_balance(std_crncy_f: str, exch_r_aplc_f: str | None = None, fee_clsf: str | None = None, cn_f: str | None = None, nxt_key: str | None = None, mktpr_aplc_clsf: str | None = None) -> dict:
    """해외주식 계좌 잔고 평가를 조회합니다.보유 중인 해외주식의 종목별 수량, 평균 단가, 현재가, 평가금액 및 손익을 확인할 수 있습니다.
    
    KB증권 API: SPQM2226 (POST /api/v1/spqm2226)
    
    Args:
        std_crncy_f: 기준통화여부 (필수). 1: 외화기준, 2: 원화기준
        exch_r_aplc_f: 환율적용여부 (선택). 1:환전시매도환율, 2: 매매기준환율(원화)
        fee_clsf: 수수료구분 (선택). 0: 포함, 1: 미포함
        cn_f: 연속여부 (선택).
        nxt_key: 다음키 (선택).
        mktpr_aplc_clsf: 시세적용구분 (선택).
    """
    body = {
        "std_crncy_f": std_crncy_f,
        "exch_r_aplc_f": exch_r_aplc_f,
        "fee_clsf": fee_clsf,
        "cn_f": cn_f,
        "nxt_key": nxt_key,
        "mktpr_aplc_clsf": mktpr_aplc_clsf,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/spqm2226", body)


@mcp.tool()
async def account_os_get_corporate_actions(rgt_clsf: str, strt_dt: str | None = None, is_cd: str | None = None, nxt_key: str | None = None) -> dict:
    """계좌에서 발생한 권리 내역을 조회합니다.배당금 지급, 주식 배당, 무상증자 등 보유 종목에서 발생한 권리 행사 내역을 확인할 수 있습니다.
    
    KB증권 API: SRQM3051 (POST /api/v1/srqm3051)
    
    Args:
        strt_dt: 시작일자 (선택).
        rgt_clsf: 권리구분 (필수). 0:전체, 1:배당, 2:유상증자/BW권리행사, 3:무상증자, 4:매수청구, 5:감자, 6:액면분할/액면병합, 7:피흡수합병
        is_cd: 종목코드 (선택).
        nxt_key: 다음키 (선택).
    """
    body = {
        "strt_dt": strt_dt,
        "rgt_clsf": rgt_clsf,
        "is_cd": is_cd,
        "nxt_key": nxt_key,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/srqm3051", body)

