"""Generated by scripts/generate_tools.py — do not edit by hand.

Regenerate with: python scripts/generate_tools.py
Source: spec/kbsec_api_spec.json + spec/tool_metadata.yaml
"""
from app import mcp
from client import call


@mcp.tool()
async def ranking_os_get_market_analysis(frex_clsf: str, clsf: str | None = None, rnk: str | None = None, is_cnt: str | None = None) -> dict:
    """해외시세분석
    
    KB증권 API: GSA10600 (POST /api/v1/gsa10600)
    
    Args:
        frex_clsf: 해외거래소구분 (필수). AA:미국전체 AB:나스닥 AC:뉴욕 AD:아멕스
        clsf: 구분 (선택). 1:전일대비 2: 시가총액 3:거래량 4:52주 신고가 5:52주 신저가 6:PER 7:EPS, 8:배당수익률, a:거래대금
        rnk: 순위 (선택). 1:상위 2:하위
        is_cnt: 종목건수 (선택).
    """
    body = {
        "frex_clsf": frex_clsf,
        "clsf": clsf,
        "rnk": rnk,
        "is_cnt": is_cnt,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/gsa10600", body)


@mcp.tool()
async def ranking_os_get_top_volume(krx_cd: str, std_dy: str | None = None, vlm: str | None = None, is_cnt: str | None = None) -> dict:
    """거래량상위
    
    KB증권 API: GSA10150 (POST /api/v1/gsa10150)
    
    Args:
        krx_cd: 거래소코드 (필수). NAS: 나스닥, NYS: 뉴욕거래소, AMX: 아멕스
        std_dy: 기준일 (선택). 01: 전일,05:5일,10:10일, 20:20일, 60:60일, 90:90일
        vlm: 거래량 (선택).
        is_cnt: 종목건수 (선택).
    """
    body = {
        "krx_cd": krx_cd,
        "std_dy": std_dy,
        "vlm": vlm,
        "is_cnt": is_cnt,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/gsa10150", body)


@mcp.tool()
async def ranking_os_get_top_market_cap(krx_cd: str, is_cnt: str | None = None) -> dict:
    """시가총액상위
    
    KB증권 API: GSA10170 (POST /api/v1/gsa10170)
    
    Args:
        krx_cd: 거래소코드 KRX_CD (필수). NAS: 나스닥, NYS: 뉴욕거래소, AMX: 아멕스
        is_cnt: 종목건수 IS_CNT (선택).
    """
    body = {
        "krx_cd": krx_cd,
        "is_cnt": is_cnt,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/gsa10170", body)


@mcp.tool()
async def ranking_os_get_new_high_low(krx_cd: str | None = None, clsf: str | None = None, clsf2: str | None = None, std_dy: str | None = None, vlm: str | None = None, is_cnt: str | None = None) -> dict:
    """신고신저
    
    KB증권 API: GSS10180 (POST /api/v1/gss10180)
    
    Args:
        krx_cd: 거래소코드 KRX_CD (선택). NAS: 나스닥, NYS: 뉴욕거래소, AMX: 아멕스
        clsf: 구분 CLSF (1:신고 2:신저) (선택). 0: 신고 1: 신저
        clsf2: 구분2 CLSF2 (1:일시돌파 2:돌파유지) (선택). 0: 일시돌파 1: 돌파유지
        std_dy: 기준일 STD_DY (01:전일 05:5일 10:10일) (선택). 01: 전일,05:5일,10:10일, 20:20일, 60:60일, 90:90일
        vlm: 거래량 VLM (선택).
        is_cnt: 종목건수 IS_CNT (선택).
    """
    body = {
        "krx_cd": krx_cd,
        "clsf": clsf,
        "clsf2": clsf2,
        "std_dy": std_dy,
        "vlm": vlm,
        "is_cnt": is_cnt,
    }
    body = {k: v for k, v in body.items() if v is not None}

    return await call("/api/v1/gss10180", body)

